ipynb-filters:
  - nbdev_filter.py

project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    left:
      - sidebar:API
      - about.qmd
      - text: App
        href: https://rahuketu86-htmxapp.hf.space
      
  sidebar:
    - id: API
      title: API
      style: docked
      contents:
        - 01_main.ipynb



